import './Home.css'

export default function Home() {
    return (
        <div className='home'>
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!
            Hello!

        </div>
    )
}
